# This file is For Deployment to Vercel
# This workflow will be triggered on pushes to the main branch and will deploy the application to Vercel.

name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npx nx build frontend

      - name: Build backend
        run: npx nx build backend

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
