name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust node version as needed
      - run: npm install
      - run: npm test
      - run: npx nx build frontend --prod
      - run: npx nx build backend --prod
      - uses: amondnet/vercel-action@v25
        with:
          token: ${{ secrets.VERCEL_TOKEN }}

