# This build is used for Nx Cloud Computation and SonarCloud Scan
# This workflow will be triggered on pushes to the main branch and will run Nx tasks in Nx Cloud, followed by a SonarCloud scan.

name: CI PIPELINE

on:
  push:
    branches:
      - main

jobs:
  nx-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Nx Cloud computation
        run: npx nx affected --target=build --all --parallel --maxParallel=4

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.organization=<your-sonarcloud-organization> \
            -Dsonar.projectKey=<your-project-key> \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
